fix(chart): Fix heatmap charts when filtering down to one row/column and normalising.
The [`pandas_postprocessing/rank.py`](superset/utils/pandas_postprocessing/rank.py) fails when a single category is found in lines/rows.

This fix correctly uses the pandas groupby->apply API not to break in that case.

A testing unit is added in [test_rank.py](tests/unit_tests/pandas_postprocessing/test_rank.py).

Closes #40709

N/A

1. Follow the steps in #40709 to reproduce the error in 6.0.0 and 6.1.0
2. Run the new unit test against the old version of the code for it to raise when the dataframe is reduced to have one category only.
3. New code correctly passes the tests and returns a working heatmap as shown in bottom of #40709

A minimal working example is:

```python
tmp_df = categories_df[categories_df["dept"]=="dept0"].reset_index(drop=True)
tmp_df.drop(columns=["rank"], errors="ignore", inplace=True)
rank_upstream(tmp_df, "asc_idx", "dept")  # Prev version
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
....
ValueError: Cannot set a DataFrame with multiple columns to the single column rank

tmp_df = categories_df[categories_df["dept"]=="dept0"].reset_index(drop=True)
tmp_df.drop(columns=["rank"], errors="ignore", inplace=True)
rank(tmp_df, "asc_idx", "dept")  # NEW version
>	constant	category	dept	name	> asc_idx	desc_idx	idx_nulls	rank
> 0	dummy	cat0	dept0	person0	0	100	0.0	0.047619
> 1	dummy	cat2	dept0	person5	5	95	5.0	0.095238
> 2	dummy	cat1	dept0	person10	10	90	10.0	0.142857
...
```

- [x] Has associated issue: #40709
- [ ] Required feature flags:
- [ ] API changes:
- [ ] DB migration required:

- [ ] CI checks pass
- [x] Tests added/updated
- [ ] Documentation updated
- [x] PR title follows conventions