fix error
 run cli cmd : superset   such as :superset db upgrade
print this

Traceback (most recent call last):
  File "/home/work/incubator-superset/superset/bin/superset", line 5, in <module>
    from flask.exthook import ExtDeprecationWarning
ModuleNotFoundError: No module named 'flask.exthook'
work@1e7cbde60a06:~/incubator-superset$ superset db upgrade

 as of Flask 1.0, flask.ext does not exist