fix: alembic's 'superset db migate' fails with CompileError
When running on the latest `master`
running a simple `superset db migrate` to generate a new
database migration fails with error

```
sqlalchemy.exc.CompileError: PostgreSQL ENUM type requires a name.
```

This addresses the issue by giving a name to that particular enum.
From my understanding, this particular enum wasn't created in
a given migration script, so it may not be enforced at the database
level, probably by choice/design. Having the name here simply
allows for alembic's migrate subcommand to run.